### ISSUE TITLE
Stimbot reacts to pinned items as to NRDB queries

### ISSUE THREAD

**Issue by zaroth** [dodgepong/stimbot#1] opened 2016-01-27 16:29 UTC
Example: http://i.share.pho.to/2b7654dd_o.png

**Comment by dodgepong** [comment] 2016-01-27 16:32
Yeah, I know about this, but I'm not sure what to do about it. Stimbot looks for the first thing enclosed in [brackets] and something about the way pinned posts work on Slack's backed makes Stimbot read the date of a pin with brackets.

I suppose I can add a check that parses the thing in brackets for a date, and if it's successful, don't search? I'll take a look. The problem is that date parsing can be really inconsistent. Fortunately I can hopefully rely on the date from Slack to be formatted a certain way, so hopefully it won't be a big deal as long as I can codify the expected format.

Thanks for the report!

**Comment by zaroth** [comment] 2016-04-23 12:36
Just for the record: on the Jinteki slack we dealt with this issue by changing syntax from `[query]` to `!card query`. [Link](https://github.com/zaroth/stimbot/commit/de45bad50bea0ba4102d6e401965540d1493a771)

**Comment by dodgepong** [comment] 2016-04-26 15:28
Fixed by changing the card query syntax to double brackets.

**Closed as completed by dodgepong** 2016-04-26 15:28 UTC
